"use client"

import { useState, useEffect } from "react"

const translations = {
  fr: {
    legal_title: "Mentions légales",
    legal_description: "Informations légales et conditions d'utilisation de nos services",

    company_info_title: "Informations sur l'entreprise",
    company_name_label: "Nom de l'entreprise",
    company_name: "Colab Office SARL",
    company_address_label: "Siège social",
    company_address: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    company_registry_label: "Registre de commerce",
    company_registry: "B051234567890",
    tax_id_label: "Matricule fiscal",
    tax_id: "1234567/A/M/000",
    publication_director_label: "Directeur de publication",
    publication_director: "Rouache Schaima",
    contact_label: "Contact",
    email_label: "Email",
    contact_email: "contact.colab.office@gmail.com",
    phone_label: "Téléphone",
    contact_phone_number: "+216 54 824 791",

    cgu_title: "Conditions générales d'utilisation",
    cgu_section_1_title: "1. Objet",
    cgu_section_1_content: "Les présentes conditions générales d'utilisation (CGU) ont pour objet de définir les modalités et conditions d'utilisation des services proposés par Colab Office, ainsi que de définir les droits et obligations des parties dans ce cadre.",
    cgu_section_2_title: "2. Acceptation des conditions",
    cgu_section_2_content: "L'utilisation de nos services implique l'acceptation pleine et entière des présentes CGU. Si vous n'acceptez pas ces conditions, vous ne devez pas utiliser nos services.",
    cgu_section_3_title: "3. Services proposés",
    cgu_section_3_content: "Colab Office propose les services suivants : Coworking space, Administrative assistance, Company creation and modification, Legal and administrative services, Business creation consulting, Secretarial and accounting services.",
    cgu_section_4_title: "4. Obligations du client",
    cgu_section_4_content: "Le client s'engage à fournir des informations exactes et à jour, respecter la législation en vigueur, régler les factures dans les délais convenus, et informer Colab Office de tout changement dans sa situation.",
    cgu_section_5_title: "5. Tarifs et paiement",
    cgu_section_5_content: "Les tarifs de nos services sont indiqués en dinars tunisiens (DT) et sont révisables. Le paiement s'effectue selon les modalités convenues lors de la signature du contrat. Tout retard de paiement pourra entraîner la suspension des services.",
    cgu_section_6_title: "6. Responsabilité",
    cgu_section_6_content: "Colab Office s'engage à fournir ses services avec diligence et professionnalisme. Notre responsabilité est limitée aux dommages directs et ne peut excéder le montant des sommes versées par le client.",
    cgu_section_7_title: "7. Résiliation",
    cgu_section_7_content: "Le contrat peut être résilié par l'une ou l'autre des parties moyennant un préavis d'un mois. La résiliation n'affecte pas les obligations déjà nées du contrat.",
    cgu_section_8_title: "8. Droit applicable",
    cgu_section_8_content: "Les présentes CGU sont soumises au droit tunisien. Tout litige sera de la compétence exclusive des tribunaux de Sousse.",

    privacy_title: "Politique de confidentialité",
    privacy_section_1_title: "Collecte des données",
    privacy_section_1_content: "Nous collectons uniquement les données personnelles nécessaires à la fourniture de nos services : nom, prénom, adresse, téléphone, email, et informations relatives à votre entreprise.",
    privacy_section_2_title: "Utilisation des données",
    privacy_section_2_content: "Vos données sont utilisées exclusivement pour la gestion de votre dossier, la facturation, et la communication relative à nos services. Elles ne sont jamais vendues ou transmises à des tiers sans votre consentement.",
    privacy_section_3_title: "Conservation des données",
    privacy_section_3_content: "Vos données sont conservées pendant la durée de notre relation contractuelle et conformément aux obligations légales de conservation des documents comptables et juridiques.",
    privacy_section_4_title: "Vos droits",
    privacy_section_4_content: "Vous disposez d'un droit d'accès, de rectification, et de suppression de vos données personnelles. Pour exercer ces droits, contactez-nous à l'adresse contact.colab.office@gmail.com.",

    cookies_title: "Politique des cookies",
    cookies_intro: "Notre site web utilise des cookies pour améliorer votre expérience de navigation et analyser le trafic. Les cookies sont de petits fichiers texte stockés sur votre appareil.",
    cookies_types_label: "Types de cookies utilisés :",
    cookie_type_technical: "Cookies techniques : nécessaires au fonctionnement du site",
    cookie_type_analytics: "Cookies analytiques : pour mesurer l'audience et améliorer le site",
    cookie_type_preferences: "Cookies de préférences : pour mémoriser vos choix",
    cookies_disable_note: "Vous pouvez désactiver les cookies dans les paramètres de votre navigateur, mais cela peut affecter le fonctionnement du site.",

    last_updated: "Dernière mise à jour : Janvier 2024",
    contact_questions: "Pour toute question concernant ces mentions légales, contactez-nous à",
    contact_questions_email: "contact.colab.office@gmail.com",
    home: "Accueil",
    about: "À propos",
    services: "Services",
    booking: "Réservation",
    contact: "Contact",

    heroTitle: "Colab Office - Espace de coworking moderne à Ariana",
    heroSubtitle: "Travaillez, collaborez, réussissez dans notre espace professionnel",
    heroDescription:
      "Espace de coworking moderne à Ariana offrant assistance administrative, création d'entreprises, domiciliation et services aux entreprises dans un environnement collaboratif.",
    getStarted: "Réserver maintenant",
    learnMore: "En savoir plus",

    locationTitle: "Notre espace à Ariana",
    locationSubtitle: "Un environnement professionnel moderne pour votre réussite",
    locationName: "Colab Office Ariana",
    locationCity: "Ariana",
    locationAddress: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    locationDescription:
      "Découvrez notre espace de coworking moderne à Ariana. Un lieu parfait pour travailler, collaborer et développer votre activité avec nos services d'assistance administrative et de domiciliation.",
    advantages: "Avantages",
    available: "Disponible",
    startingFrom: "À partir de",
    perMonth: "/mois",
    perHour: "/heure",
    legal: "Mentions légales",  
    privacy: "Confidentialité",
    copyright: "© 2025 Colab Office - Tous droits réservés",

    // Features
    studyZones: "Espaces de travail silencieux",
    coworkingSpace: "Espace de coworking collaboratif",
    meetingRooms: "Salles de réunion équipées",
    highSpeedWifi: "WiFi haut débit",
    parkingAvailable: "Parking disponible",
    publicTransport: "Transport public accessible",
    modernOffices: "Bureaux modernes",
    reception: "Service d'accueil professionnel",
    quietEnvironment: "Environnement calme et productif",
    adminServices: "Assistance administrative",
    companyCreation: "Création d'entreprises",
    domiciliation: "Services de domiciliation",

    // Booking
    bookingTitle: "Réservez votre espace",
    selectSpace: "Sélectionnez votre espace",
    availableSpaces: "Espaces disponibles",
    reservedSpaces: "Espaces réservés",
    room1: "Salle 1 - Espace Collaboratif",
    room2: "Salle 2 - Zone Silencieuse",
    selectRoom: "Choisir la salle",

    // Services
    servicesTitle: "Nos Services",
    servicesSubtitle: "Solutions complètes pour votre activité professionnelle",
    coworkingService: "Espace de coworking moderne",
    coworkingDesc: "Espaces de travail flexibles dans un environnement collaboratif et inspirant",
    adminService: "Assistance administrative",
    adminDesc: "Support complet pour vos démarches administratives et gestion d'entreprise",
    domiciliationService: "Domiciliation d'entreprise",
    domiciliationDesc: "Adresse professionnelle prestigieuse pour votre société à Ariana",
    companyService: "Création d'entreprises",
    companyDesc: "Accompagnement personnalisé dans toutes vos démarches de création d'entreprise",

    whatsapp: {
      online: "En ligne",
      welcome: "Bonjour! Comment pouvons-nous vous aider aujourd'hui?",
      quickMessages: "Messages rapides",
      placeholder: "Tapez votre message...",
      message1: "Je souhaite réserver un espace de travail",
      message2: "Quels sont vos tarifs et services?",
      message3: "Je veux visiter l'espace",
    },
  },
  en: {
    legal_title: "Legal Notice",
    legal_description: "Legal information and terms of use of our services",

    company_info_title: "Company Information",
    company_name_label: "Company Name",
    company_name: "Colab Office SARL",
    company_address_label: "Head Office",
    company_address: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    company_registry_label: "Commercial Registry",
    company_registry: "B051234567890",
    tax_id_label: "Tax ID",
    tax_id: "1234567/A/M/000",
    publication_director_label: "Publication Director",
    publication_director: "Rouache Schaima",
    contact_label: "Contact",
    email_label: "Email",
    contact_email: "contact.colab.office@gmail.com",
    phone_label: "Phone",
    contact_phone_number: "+216 54 824 791",

    cgu_title: "Terms of Use",  
    cgu_section_1_title: "1. Purpose",
    cgu_section_1_content: "These terms of use (TOU) define the conditions for using Colab Office's services and the rights and obligations of the parties involved.",
    cgu_section_2_title: "2. Acceptance of Terms",
    cgu_section_2_content: "Using our services implies full acceptance of these TOU. If you do not accept these terms, you must not use our services.",
    cgu_section_3_title: "3. Services Offered",
    cgu_section_3_content: "Colab Office offers the following services: Coworking space, Administrative assistance, Company creation and modification, Legal and administrative services, Business creation consulting, Secretarial and accounting services.",
    cgu_section_4_title: "4. Client Obligations",
    cgu_section_4_content: "The client agrees to provide accurate and up-to-date information, comply with applicable laws, pay invoices on time, and inform Colab Office of any changes in their situation.",
    cgu_section_5_title: "5. Pricing and Payment",
    cgu_section_5_content: "Service fees are indicated in Tunisian Dinar (DT) and may be revised. Payment is made according to the agreed terms at contract signing. Late payment may result in service suspension.",
    cgu_section_6_title: "6. Liability",
    cgu_section_6_content: "Colab Office commits to providing its services with diligence and professionalism. Liability is limited to direct damages and cannot exceed the amounts paid by the client.",
    cgu_section_7_title: "7. Termination",
    cgu_section_7_content: "The contract can be terminated by either party with one month's notice. Termination does not affect obligations already arisen.",
    cgu_section_8_title: "8. Governing Law",
    cgu_section_8_content: "These TOU are governed by Tunisian law. Any disputes fall under the exclusive jurisdiction of Sousse courts.",

    privacy_title: "Privacy Policy",
    privacy_section_1_title: "Data Collection",
    privacy_section_1_content: "We only collect personal data necessary for providing our services: name, surname, address, phone, email, and company information.",
    privacy_section_2_title: "Data Use",
    privacy_section_2_content: "Your data is used exclusively for file management, billing, and communication regarding our services. They are never sold or shared without consent.",
    privacy_section_3_title: "Data Retention",
    privacy_section_3_content: "Your data is retained during our contractual relationship and in accordance with legal obligations for accounting and legal document retention.",
    privacy_section_4_title: "Your Rights",
    privacy_section_4_content: "You have the right to access, correct, and delete your personal data. To exercise these rights, contact us at contact.colab.office@gmail.com.",

    cookies_title: "Cookie Policy",
    cookies_intro: "Our website uses cookies to enhance your browsing experience and analyze traffic. Cookies are small text files stored on your device.",
    cookies_types_label: "Types of cookies used:",
    cookie_type_technical: "Technical cookies: necessary for site functionality",
    cookie_type_analytics: "Analytics cookies: to measure audience and improve the site",
    cookie_type_preferences: "Preference cookies: to remember your choices",
    cookies_disable_note: "You can disable cookies in your browser settings, but this may affect site functionality.",

    last_updated: "Last update: January 2024",
    contact_questions: "For any questions regarding this legal notice, contact us at",
    contact_questions_email: "contact.colab.office@gmail.com",
    home: "Home",
    about: "About",
    services: "Services",
    booking: "Booking",
    contact: "Contact",

    heroTitle: "Colab Office - Modern coworking space in Ariana",
    heroSubtitle: "Work, collaborate, succeed in our professional environment",
    heroDescription:
      "Modern coworking space in Ariana offering administrative assistance, company creation, domiciliation and business services in a collaborative environment.",
    getStarted: "Book Now",
    learnMore: "Learn More",

    // Location Section
    locationTitle: "Our space in Ariana",
    locationSubtitle: "A modern professional environment for your success",
    locationName: "Colab Office Ariana",
    locationCity: "Ariana",
    locationAddress: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    locationDescription:
      "Discover our modern coworking space in Ariana. A perfect place to work, collaborate and develop your business with our administrative assistance and domiciliation services.",
    advantages: "Advantages",
    available: "Available",
    startingFrom: "Starting from",
    perMonth: "/month",
    perHour: "/hour",
    legal: "Legal",
    privacy: "Privacy",
    copyright: "© 2025 Colab Office - All rights reserved",

    // Features
    studyZones: "Quiet work spaces",
    coworkingSpace: "Collaborative coworking space",
    meetingRooms: "Equipped meeting rooms",
    highSpeedWifi: "High-speed WiFi",
    parkingAvailable: "Parking available",
    publicTransport: "Public transport accessible",
    modernOffices: "Modern offices",
    reception: "Professional reception service",
    quietEnvironment: "Calm and productive environment",
    adminServices: "Administrative assistance",
    companyCreation: "Company creation",
    domiciliation: "Domiciliation services",

    // Booking
    bookingTitle: "Book your space",
    selectSpace: "Select your space",
    availableSpaces: "Available spaces",
    reservedSpaces: "Reserved spaces",
    room1: "Room 1 - Collaborative Space",
    room2: "Room 2 - Quiet Zone",
    selectRoom: "Choose room",

    // Services
    servicesTitle: "Our Services",
    servicesSubtitle: "Complete solutions for your professional activity",
    coworkingService: "Modern coworking space",
    coworkingDesc: "Flexible workspaces in a collaborative and inspiring environment",
    adminService: "Administrative assistance",
    adminDesc: "Complete support for your administrative procedures and business management",
    domiciliationService: "Business domiciliation",
    domiciliationDesc: "Prestigious professional address for your company in Ariana",
    companyService: "Company creation",
    companyDesc: "Personalized support in all your company creation procedures",

    // WhatsApp translations
    whatsapp: {
      online: "Online",
      welcome: "Hello! How can we help you today?",
      quickMessages: "Quick messages",
      placeholder: "Type your message...",
      message1: "I want to book a workspace",
      message2: "What are your rates and services?",
      message3: "I want to visit the space",
    },
  },
  ar: {
    legal_title: "الشروط والأحكام",
    legal_description: "المعلومات القانونية وشروط استخدام خدماتنا",

    company_info_title: "معلومات الشركة",
    company_name_label: "اسم الشركة",
    company_name: "شركة رايز سيرفيسز",
    company_address_label: "المقر الرئيسي",
    company_address: "شارع ياسر عرفات، سوسة 4054، تونس",
    company_registry_label: "السجل التجاري",
    company_registry: "B051234567890",
    tax_id_label: "الرقم الضريبي",
    tax_id: "1234567/A/M/000",
    publication_director_label: "مدير النشر",
    publication_director: "أحمد صالحي",
    contact_label: "الاتصال",
    email_label: "البريد الإلكتروني",
    contact_email: "contact.colab.office@gmail.com",
    phone_label: "الهاتف",
    contact_phone_number: "+216 54 824 791",

    cgu_title: "الشروط والأحكام",
    cgu_section_1_title: "1. الهدف",
    cgu_section_1_content: "تهدف هذه الشروط لتحديد شروط استخدام خدمات كولاب أوفيس وحقوق والتزامات الأطراف.",
    cgu_section_2_title: "2. قبول الشروط",
    cgu_section_2_content: "استخدام خدماتنا يعني القبول الكامل لهذه الشروط. إذا لم توافق على هذه الشروط، يجب عدم استخدام خدماتنا.",
    cgu_section_3_title: "3. الخدمات المقدمة",
    cgu_section_3_content: "تقدم رايز سيرفيسز الخدمات التالية: التسكين، إنشاء وتعديل الشركات، الخدمات القانونية والإدارية، الاستشارات في إنشاء الشركات، خدمات السكرتارية والمحاسبة.",
    cgu_section_4_title: "4. التزامات العميل",
    cgu_section_4_content: "يجب على العميل تقديم معلومات دقيقة ومحدثة، الالتزام بالقوانين، دفع الفواتير في الوقت المحدد، وإبلاغ رايز سيرفيسز بأي تغييرات في وضعه.",
    cgu_section_5_title: "5. الأسعار والدفع",
    cgu_section_5_content: "الأسعار بالعملة التونسية (DT) وقابلة للتعديل. يتم الدفع وفق الشروط المتفق عليها عند توقيع العقد. التأخير في الدفع قد يؤدي إلى تعليق الخدمات.",
    cgu_section_6_title: "6. المسؤولية",
    cgu_section_6_content: "تلتزم رايز سيرفيسز بتقديم خدماتها بمهارة ومهنية. المسؤولية محدودة بالأضرار المباشرة ولا تتجاوز المبالغ المدفوعة من قبل العميل.",
    cgu_section_7_title: "7. إنهاء العقد",
    cgu_section_7_content: "يمكن لأي طرف إنهاء العقد مع إشعار مسبق لمدة شهر. لا يؤثر الإنهاء على الالتزامات المتحققة بالفعل.",
    cgu_section_8_title: "8. القانون المطبق",
    cgu_section_8_content: "تخضع هذه الشروط للقانون التونسي. أي نزاعات تكون من اختصاص محاكم سوسة.",

    privacy_title: "سياسة الخصوصية",
    privacy_section_1_title: "جمع البيانات",
    privacy_section_1_content: "نقوم بجمع البيانات الشخصية الضرورية فقط لتقديم خدماتنا: الاسم، العنوان، الهاتف، البريد الإلكتروني، ومعلومات الشركة.",
    privacy_section_2_title: "استخدام البيانات",
    privacy_section_2_content: "يتم استخدام بياناتك فقط لإدارة ملفك، الفوترة، والتواصل بخصوص خدماتنا. لا يتم بيعها أو نقلها لطرف ثالث بدون موافقتك.",
    privacy_section_3_title: "الاحتفاظ بالبيانات",
    privacy_section_3_content: "يتم الاحتفاظ ببياناتك طوال فترة العلاقة التعاقدية ووفق الالتزامات القانونية للوثائق المحاسبية والقانونية.",
    privacy_section_4_title: "حقوقك",
    privacy_section_4_content: "لديك الحق في الوصول إلى بياناتك الشخصية وتصحيحها وحذفها. لممارسة هذه الحقوق، اتصل بنا على contact@riseservices.tn.",

    cookies_title: "سياسة الكوكيز",
    cookies_intro: "يستخدم موقعنا ملفات الكوكيز لتحسين تجربة التصفح وتحليل الحركة. الكوكيز هي ملفات نصية صغيرة مخزنة على جهازك.",
    cookies_types_label: "أنواع الكوكيز المستخدمة:",
    cookie_type_technical: "كوكيز تقنية: ضرورية لتشغيل الموقع",
    cookie_type_analytics: "كوكيز تحليلية: لقياس الجمهور وتحسين الموقع",
    cookie_type_preferences: "كوكيز تفضيلات: لحفظ اختياراتك",
    cookies_disable_note: "يمكنك تعطيل الكوكيز في إعدادات المتصفح، لكن هذا قد يؤثر على عمل الموقع.",

    last_updated: "آخر تحديث: يناير 2024",
    contact_questions: "لأي استفسارات حول الشروط والأحكام، اتصل بنا على",
    contact_questions_email: "contact.colab.office@gmail.com",
    home: "الرئيسية",
    about: "حولنا",
    services: "الخدمات",
    booking: "الحجز",
    contact: "اتصل بنا",

    heroTitle: "كولاب أوفيس - مساحة عمل مشتركة حديثة في أريانة",
    heroSubtitle: "اعمل، تعاون، انجح في بيئتنا المهنية",
    heroDescription:
      "مساحة عمل مشتركة حديثة في أريانة تقدم المساعدة الإدارية وإنشاء الشركات والتسكين وخدمات الأعمال في بيئة تعاونية.",
    getStarted: "احجز الآن",
    learnMore: "اعرف المزيد",

    locationTitle: "مساحتنا في أريانة",
    locationSubtitle: "بيئة مهنية حديثة لنجاحك",
    locationName: "كولاب أوفيس أريانة",
    locationCity: "أريانة",
    locationAddress: "14 شارع ابن الهاني (دوار برج لوزير)، أريانة",
    locationDescription:
      "اكتشف مساحة العمل المشتركة الحديثة في أريانة. مكان مثالي للعمل والتعاون وتطوير أعمالك مع خدمات المساعدة الإدارية والتسكين.",
    advantages: "المزايا",
    available: "متاح",
    startingFrom: "ابتداء من",
    perMonth: "/شهر",
    perHour: "/ساعة",
    legal: "الشروط والأحكام",
    privacy: "الخصوصية",
    
    studyZones: "مساحات عمل هادئة",
    coworkingSpace: "مساحة عمل مشتركة تعاونية",
    meetingRooms: "قاعات اجتماعات مجهزة",
    highSpeedWifi: "إنترنت عالي السرعة",
    parkingAvailable: "موقف سيارات متاح",
    publicTransport: "النقل العام متاح",
    modernOffices: "مكاتب حديثة",
    reception: "خدمة استقبال مهنية",
    quietEnvironment: "بيئة هادئة ومنتجة",
    adminServices: "المساعدة الإدارية",
    companyCreation: "إنشاء الشركات",
    domiciliation: "خدمات التسكين",
    copyright: "© 2025 كولاب أوفيس - جميع الحقوق محفوظة",

    bookingTitle: "احجز مساحتك",
    selectSpace: "اختر مساحتك",
    availableSpaces: "المساحات المتاحة",
    reservedSpaces: "المساحات المحجوزة",
    room1: "القاعة 1 - مساحة تعاونية",
    room2: "القاعة 2 - منطقة هادئة",
    selectRoom: "اختر القاعة",

    servicesTitle: "خدماتنا",
    servicesSubtitle: "حلول شاملة لنشاطك المهني",
    coworkingService: "مساحة عمل مشتركة حديثة",
    coworkingDesc: "مساحات عمل مرنة في بيئة تعاونية وملهمة",
    adminService: "المساعدة الإدارية",
    adminDesc: "دعم كامل لإجراءاتك الإدارية وإدارة الأعمال",
    domiciliationService: "تسكين الشركات",
    domiciliationDesc: "عنوان مهني مرموق لشركتك في أريانة",
    companyService: "إنشاء الشركات",
    companyDesc: "مرافقة شخصية في جميع إجراءات إنشاء شركتك",

    whatsapp: {
      online: "متصل",
      welcome: "مرحبا! كيف يمكننا مساعدتك اليوم؟",
      quickMessages: "رسائل سريعة",
      placeholder: "اكتب رسالتك...",
      message1: "أريد حجز مساحة عمل",
      message2: "ما هي أسعاركم وخدماتكم؟",
      message3: "أريد زيارة المكان",
    },
  },
}

export function useLanguage() {
  const [currentLang, setCurrentLang] = useState("fr")

  useEffect(() => {
    const savedLang = localStorage.getItem("preferred-language") || "fr"
    setCurrentLang(savedLang)

    const handleLanguageChange = (event: CustomEvent) => {
      setCurrentLang(event.detail)
    }

    window.addEventListener("languageChange", handleLanguageChange as EventListener)

    return () => {
      window.removeEventListener("languageChange", handleLanguageChange as EventListener)
    }
  }, [])

  const t = (key: string) => {
    return translations[currentLang as keyof typeof translations]?.[key as keyof (typeof translations)["fr"]] || key
  }

  return { currentLang, t }
}
