"use client"

import { useState, useEffect } from "react"

const translations = {
  fr: {
    // Add to the French translations object
premiumWorkspace: "Espace de travail premium",
heroTitlePart1: "Espace de travail",
heroTitlePart2: "productif & moderne",
heroSubtitle: "Travaillez, collaborez, réussissez dans notre espace professionnel moderne à Ariana. Réservez votre espace dès maintenant.",
reserve: "Réserver maintenant",
contact: "Nous contacter",
satisfactionRate: "Taux de satisfaction",
availability: "Disponibilité",
happyMembers: "Membres satisfaits",
freeHighSpeedWifi: "WiFi Haut Débit Gratuit",
equippedMeetingRooms: "Salles de Réunion Équipées",
refreshmentsIncluded: "Rafraîchissements Inclus",
wifiDescription: "Connexion ultra-rapide pour un travail sans interruption",
meetingRoomsDescription: "Salles modernes avec équipement complet pour vos réunions",
refreshmentsDescription: "Café, thé et collations disponibles toute la journée",
locationAddress: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
easyAccess: "Accès facile, parking disponible",
    bookingHeroTitle: "Réservez votre espace",
    bookingHeroSubtitle: "Choisissez l'espace parfait pour votre productivité",
    bookingLocation: "Ariana, Tunisie",
    
    // Room Selection
    selectSpaceTitle: "Sélectionnez votre espace - Colab Office Ariana",
    studyZone1: "Zone d'étude 1",
    studyZone2: "Zone d'étude 2",
    trainingRoom: "Salle de Formation",
    meetingRoom: "Salle de Réunion",
    wholeRoomEquipment: "Salle entière avec équipement professionnel",
    quietProductiveArea: "Espace calme et productif pour concentration maximale",
    
    // Legend
    studyZoneLegend: "Zone d'étude (15 DT/jour)",
    trainingRoomLegend: "Formation (150 DT/jour)",
    meetingRoomLegend: "Réunion (80 DT/jour)",
    occupiedLegend: "Occupé",
    
    // Room Names
    quietStudyZone1: "Zone d'étude silencieuse 1",
    quietStudyZone2: "Zone d'étude silencieuse 2",
    trainingRoomName: "Salle de Formation",
    meetingRoomName: "Salle de Réunion",
    entranceLabel: "Entrée",
    
    // Booking Form
    bookingFormTitle: "Réservation",
    completeRoom: "Salle complète",
    place: "Place",
    persons: "personnes",
    
    // Duration Prices
    twoHours: "2 heures",
    halfDay: "Demi-journée",
    fullDay: "Journée complète",
    
    // Space Types
    studyZoneType: "Zone d'étude",
    trainingRoomType: "Salle de Formation",
    meetingRoomType: "Salle de Réunion",
    spaceType: "Espace",
    
    // Features Section
    bookingFeaturesTitle: "Pourquoi choisir Colab Office ?",
    bookingFeaturesSubtitle: "Un environnement moderne et professionnel pour votre productivité",
    
    // Feature Cards
    quietEnvironmentFeature: "Environnement calme",
    quietEnvironmentDesc: "Zone silencieuse garantie pour votre concentration",
    flexibleHoursFeature: "Horaires flexibles",
    flexibleHoursDesc: "Ouvert de 8h à 22h, 7 jours sur 7",
    completeServicesFeature: "Services complets",
    completeServicesDesc: "Assistance administrative et création d'entreprises",
    idealLocationFeature: "Emplacement idéal",
    idealLocationDesc: "Au cœur d'Ariana, facilement accessible",
    
    // Booking Form Fields
    selectDate: "Date",
    startTime: "Heure de début",
    selectTime: "Sélectionner l'heure",
    durationLabel: "Durée",
    totalLabel: "Total",
    
    // Actions
    bookNowButton: "Réserver maintenant",
    selectSpaceButton: "Sélectionnez une place",
    selectSpacePrompt: "Cliquez sur une place disponible pour commencer votre réservation",
    
    // Messages
    securePayment: "Paiement sécurisé",
    freeCancellation: "Annulation gratuite jusqu'à 2h avant",
    perDay: "/jour",
    
    // Time slots
    hours: [
      "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", 
      "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", 
      "20:00", "21:00"
    ],
    
    // Additional Booking Info
    capacity: "Capacité",
    includes: "Comprend",
    dayRate: "Tarif journée",
    halfDayRate: "Tarif demi-journée",
    twoHoursRate: "Tarif 2 heures",
    
    // Room Features
    projector: "Projecteur",
    whiteboard: "Tableau blanc",
    wifi: "WiFi",
    airConditioning: "Climatisation",
    seats: "places",
    tvScreen: "Écran TV",
    videoConference: "Visioconférence",
    silence: "Silence",
    powerOutlet: "Prise électrique",
    // Services Page
servicesPageTitle: "Rise Services - Nos Solutions",
servicesPageSubtitle: "Espace de coworking moderne, assistance administrative et services aux entreprises à Ariana",
mainServicesTitle: "Nos Services Principaux",
mainServicesSubtitle: "Solutions complètes pour votre activité professionnelle dans un environnement moderne",
collaborative: "Collaboratif",
openPrivateSpaces: "Espaces ouverts et privés",
freeHighSpeedWifi: "WiFi haut débit gratuit",
equippedMeetingRooms: "Salles de réunion équipées",
freeCoffeeTea: "Café et thé gratuits",
perHour: "/heure",
reserve: "Réserver",
concentration: "Concentration",
studyZonesTitle: "Zones d'étude silencieuses",
studyZonesDesc: "Espaces dédiés à l'étude dans un environnement calme et concentré",
silenceGuaranteed: "Silence garanti",
electricOutlets: "Prises électriques à chaque place",
optimalLighting: "Éclairage optimal",
completeSupport: "Support complet",
adminServiceTitle: "Assistance administrative",
adminServiceDesc: "Support complet pour vos démarches administratives et gestion d'entreprise",
companyCreationService: "Création d'entreprises",
adminFormalities: "Formalités administratives",
legalAdvice: "Conseil juridique",
personalizedSupport: "Accompagnement personnalisé",
onQuote: "Sur devis",
consult: "Consulter",
prestigiousAddress: "Adresse prestigieuse",
domiciliationTitle: "Domiciliation d'entreprise",
domiciliationDesc: "Adresse professionnelle prestigieuse pour votre société à Ariana",
prestigiousCommercialAddress: "Adresse commerciale prestigieuse",
mailReception: "Réception du courrier",
phoneService: "Permanence téléphonique",
meetingRoomIncluded: "Salle de réunion incluse",
perMonth: "/mois",
getInfo: "S'informer",
includedServicesTitle: "Services inclus",
includedServicesSubtitle: "Tous nos espaces incluent ces services pour votre confort et productivité",
highSpeedWifiTitle: "WiFi haut débit",
highSpeedWifiDesc: "Connexion internet rapide et stable",
free: "Gratuit",
coffeeTea: "Café & Thé",
coffeeTeaDesc: "Boissons chaudes à volonté",
electricOutletsTitle: "Prises électriques",
electricOutletsDesc: "À chaque place de travail",
included: "Inclus",
quietEnvironmentTitle: "Environnement calme",
quietEnvironmentDesc: "Zones silencieuses garanties",
guaranteed: "Garanti",
readyToDiscover: "Prêt à découvrir Rise Services ?",
ctaServicesText: "Travaillez, collaborez, réussissez dans notre espace moderne à Ariana",
reserveSpace: "Réserver un espace",

    companyService: "Création d'entreprises",
    companyDesc: "Accompagnement personnalisé dans toutes vos démarches de création d'entreprise",

    // About Page - ADD THESE
    aboutTitle: "À propos de Colab Office",
    aboutSubtitle: "Votre partenaire de confiance pour tous vos besoins d'entreprise en Tunisie. Nous accompagnons les entrepreneurs dans leur réussite depuis plus de 10 ans.",
    ourMission: "Notre Mission",
    missionText1: "Chez Colab Office, nous croyons que chaque entrepreneur mérite un accompagnement professionnel et personnalisé. Notre mission est de simplifier les démarches administratives et juridiques pour permettre aux entreprises de se concentrer sur leur cœur de métier.",
    missionText2: "Nous offrons des solutions complètes incluant l'assistance administrative & création de sociétés, la domiciliation & services aux entreprises, ainsi qu'un espace de coworking moderne à Ariana pour favoriser la collaboration et la réussite professionnelle.",
    companiesSupported: "Entreprises accompagnées",
    yearsExperience: "Années d'expérience",
    isoCertified: "Certifié ISO 9001",
    qualityGuaranteed: "Qualité garantie",
    ourValues: "Nos Valeurs",
    valuesPrinciples: "Les principes qui guident notre travail au quotidien",
    trust: "Confiance",
    trustDesc: "Transparence et intégrité dans toutes nos relations clients",
    excellence: "Excellence",
    excellenceDesc: "Qualité de service irréprochable et expertise reconnue",
    responsiveness: "Réactivité",
    responsivenessDesc: "Réponses rapides et traitement efficace de vos demandes",
    proximity: "Proximité",
    proximityDesc: "Accompagnement personnalisé et relation de proximité",
    readyToStart: "Prêt à démarrer votre projet ?",
    ctaText: "Bénéficiez de notre assistance administrative & création de sociétés, domiciliation & services aux entreprises dans notre espace moderne à Ariana",
    contactUs: "Nous contacter",

    contactTitle: "Contactez-nous",
    contactSubtitle: "Notre équipe est à votre disposition pour répondre à toutes vos questions et vous accompagner dans vos projets",
    contactFormTitle: "Envoyez-nous un message",
    firstName: "Prénom *",
    firstNamePlaceholder: "Votre prénom",
    lastName: "Nom *",
    lastNamePlaceholder: "Votre nom",
    email: "Email *",
    emailPlaceholder: "votre.email@exemple.com",
    phone: "Téléphone",
    phonePlaceholder: "+216 XX XXX XXX",
    company: "Entreprise",
    companyPlaceholder: "Nom de votre entreprise",
    service: "Service souhaité",
    selectService: "Sélectionnez un service",
    serviceDomiciliation: "Domiciliation d'entreprise",
    serviceCreation: "Création d'entreprise",
    serviceJuridique: "Services juridiques",
    serviceComptabilite: "Comptabilité",
    serviceConsultation: "Consultation gratuite",
    serviceOther: "Autre",
    budget: "Budget approximatif",
    selectBudget: "Sélectionnez votre budget",
    budgetLess500: "Moins de 500 DT",
    budget5001000: "500 - 1000 DT",
    budget10002000: "1000 - 2000 DT",
    budgetMore2000: "Plus de 2000 DT",
    budgetMonthly: "Abonnement mensuel",
    message: "Message *",
    messagePlaceholder: "Décrivez votre projet ou vos besoins en détail...",
    urgentRequest: "Demande urgente (réponse sous 2h pendant les heures ouvrables)",
    sendMessage: "Envoyer le message",
    requiredFieldsNotice: "* Champs obligatoires. Nous vous répondrons dans les 24h (2h pour les demandes urgentes).",
    contactInfoTitle: "Nos coordonnées",
    address: "Adresse",
    addressLine1: "Avenue Yasser Arafat",
    addressLine2: "Sousse 4054, Tunisie",
    openingHours: "Horaires d'ouverture",
    hoursWeekdays: "Lundi - Vendredi: 8h00 - 18h00",
    hoursSaturday: "Samedi: 8h00 - 13h00",
    hoursSunday: "Dimanche: Fermé",
    quickContactTitle: "Besoin d'une réponse rapide ?",
    quickContactText: "Pour une consultation urgente, appelez-nous directement ou envoyez-nous un WhatsApp.",
    callNow: "Appeler maintenant",
    whatsapp: "WhatsApp",
    findUsTitle: "Nous trouver",
    findUsSubtitle: "Situés au cœur de Sousse, nous sommes facilement accessibles",
    mapTitle: "Carte interactive",
    mapAddress: "Avenue Yasser Arafat, Sousse 4054",
    faqTitle: "Questions fréquentes",
    faqSubtitle: "Les réponses aux questions les plus courantes",
    faq1Question: "Combien de temps faut-il pour obtenir une adresse de domiciliation ?",
    faq1Answer: "Une fois votre dossier complet reçu, nous pouvons vous fournir votre attestation de domiciliation sous 24 à 48 heures ouvrables. Pour les demandes urgentes, nous proposons un service express sous 4 heures.",
    faq2Question: "Quels documents sont nécessaires pour la domiciliation ?",
    faq2Answer: "Vous aurez besoin de vos statuts de société, d'une copie de votre CIN, du formulaire de demande de domiciliation dûment rempli, et d'un justificatif d'activité. Notre équipe vous accompagne dans la constitution du dossier.",
    faq3Question: "Proposez-vous des services dans d'autres villes ?",
    faq3Answer: "Oui, nous avons des partenaires dans les principales villes de Tunisie : Tunis, Sfax, Monastir, Nabeul, et Gabès. Nous proposons les mêmes services avec la même qualité dans toutes ces villes.",
    faq4Question: "Puis-je changer de formule en cours d'abonnement ?",
    faq4Answer: "Absolument ! Vous pouvez upgrader ou downgrader votre formule à tout moment. Les changements prennent effet le mois suivant et nous ajustons la facturation au prorata.",
    faq5Question: "Offrez-vous une consultation gratuite ?",
    faq5Answer: "Oui, nous offrons une consultation gratuite de 30 minutes pour évaluer vos besoins et vous conseiller sur la meilleure solution. Prenez rendez-vous via notre formulaire de contact.",
    legal_title: "Mentions légales",
    legal_description: "Informations légales et conditions d'utilisation de nos services",

    company_info_title: "Informations sur l'entreprise",
    company_name_label: "Nom de l'entreprise",
    company_name: "Colab Office SARL",
    company_address_label: "Siège social",
    company_address: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    company_registry_label: "Registre de commerce",
    company_registry: "B051234567890",
    tax_id_label: "Matricule fiscal",
    tax_id: "1234567/A/M/000",
    publication_director_label: "Directeur de publication",
    publication_director: "Rouache Schaima",
    contact_label: "Contact",
    email_label: "Email",
    contact_email: "contact.colab.office@gmail.com",
    phone_label: "Téléphone",
    contact_phone_number: "+216 54 824 791",

    cgu_title: "Conditions générales d'utilisation",
    cgu_section_1_title: "1. Objet",
    cgu_section_1_content: "Les présentes conditions générales d'utilisation (CGU) ont pour objet de définir les modalités et conditions d'utilisation des services proposés par Colab Office, ainsi que de définir les droits et obligations des parties dans ce cadre.",
    cgu_section_2_title: "2. Acceptation des conditions",
    cgu_section_2_content: "L'utilisation de nos services implique l'acceptation pleine et entière des présentes CGU. Si vous n'acceptez pas ces conditions, vous ne devez pas utiliser nos services.",
    cgu_section_3_title: "3. Services proposés",
    cgu_section_3_content: "Colab Office propose les services suivants : Coworking space, Administrative assistance, Company creation and modification, Legal and administrative services, Business creation consulting, Secretarial and accounting services.",
    cgu_section_4_title: "4. Obligations du client",
    cgu_section_4_content: "Le client s'engage à fournir des informations exactes et à jour, respecter la législation en vigueur, régler les factures dans les délais convenus, et informer Colab Office de tout changement dans sa situation.",
    cgu_section_5_title: "5. Tarifs et paiement",
    cgu_section_5_content: "Les tarifs de nos services sont indiqués en dinars tunisiens (DT) et sont révisables. Le paiement s'effectue selon les modalités convenues lors de la signature du contrat. Tout retard de paiement pourra entraîner la suspension des services.",
    cgu_section_6_title: "6. Responsabilité",
    cgu_section_6_content: "Colab Office s'engage à fournir ses services avec diligence et professionnalisme. Notre responsabilité est limitée aux dommages directs et ne peut excéder le montant des sommes versées par le client.",
    cgu_section_7_title: "7. Résiliation",
    cgu_section_7_content: "Le contrat peut être résilié par l'une ou l'autre des parties moyennant un préavis d'un mois. La résiliation n'affecte pas les obligations déjà nées du contrat.",
    cgu_section_8_title: "8. Droit applicable",
    cgu_section_8_content: "Les présentes CGU sont soumises au droit tunisien. Tout litige sera de la compétence exclusive des tribunaux de Sousse.",

    privacy_title: "Politique de confidentialité",
    privacy_section_1_title: "Collecte des données",
    privacy_section_1_content: "Nous collectons uniquement les données personnelles nécessaires à la fourniture de nos services : nom, prénom, adresse, téléphone, email, et informations relatives à votre entreprise.",
    privacy_section_2_title: "Utilisation des données",
    privacy_section_2_content: "Vos données sont utilisées exclusivement pour la gestion de votre dossier, la facturation, et la communication relative à nos services. Elles ne sont jamais vendues ou transmises à des tiers sans votre consentement.",
    privacy_section_3_title: "Conservation des données",
    privacy_section_3_content: "Vos données sont conservées pendant la durée de notre relation contractuelle et conformément aux obligations légales de conservation des documents comptables et juridiques.",
    privacy_section_4_title: "Vos droits",
    privacy_section_4_content: "Vous disposez d'un droit d'accès, de rectification, et de suppression de vos données personnelles. Pour exercer ces droits, contactez-nous à l'adresse contact.colab.office@gmail.com.",

    cookies_title: "Politique des cookies",
    cookies_intro: "Notre site web utilise des cookies pour améliorer votre expérience de navigation et analyser le trafic. Les cookies sont de petits fichiers texte stockés sur votre appareil.",
    cookies_types_label: "Types de cookies utilisés :",
    cookie_type_technical: "Cookies techniques : nécessaires au fonctionnement du site",
    cookie_type_analytics: "Cookies analytiques : pour mesurer l'audience et améliorer le site",
    cookie_type_preferences: "Cookies de préférences : pour mémoriser vos choix",
    cookies_disable_note: "Vous pouvez désactiver les cookies dans les paramètres de votre navigateur, mais cela peut affecter le fonctionnement du site.",

    last_updated: "Dernière mise à jour : Janvier 2024",
    contact_questions: "Pour toute question concernant ces mentions légales, contactez-nous à",
    contact_questions_email: "contact.colab.office@gmail.com",
    home: "Accueil",
    about: "À propos",
    services: "Services",
    booking: "Réservation",
    contact: "Contact",
    faq: "FAQ",
    mapCity: "Tunis, Tunisie",
    getDirections: "Obtenir l'itinéraire",
    callUs: "Nous appeler",
    seeOnGoogleMaps: "Voir sur Google Maps",

    heroTitle: "Colab Office - Espace de coworking moderne à Ariana",
    heroSubtitle: "Travaillez, collaborez, réussissez dans notre espace professionnel",
    heroDescription:
      "Espace de coworking moderne à Ariana offrant assistance administrative, création d'entreprises, domiciliation et services aux entreprises dans un environnement collaboratif.",
    getStarted: "Réserver maintenant",
    learnMore: "En savoir plus",

    locationTitle: "Notre espace à Ariana",
    locationSubtitle: "Un environnement professionnel moderne pour votre réussite",
    locationName: "Colab Office Ariana",
    locationCity: "Ariana",
    locationAddress: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    locationDescription:
      "Découvrez notre espace de coworking moderne à Ariana. Un lieu parfait pour travailler, collaborer et développer votre activité avec nos services d'assistance administrative et de domiciliation.",
    advantages: "Avantages",
    available: "Disponible",
    startingFrom: "À partir de",
    perMonth: "/mois",
    perHour: "/heure",
    legal: "Mentions légales",  
    privacy: "Confidentialité",
    copyright: "© 2025 Colab Office - Tous droits réservés",

    // Features
    studyZones: "Espaces de travail silencieux",
    coworkingSpace: "Espace de coworking collaboratif",
    meetingRooms: "Salles de réunion équipées",
    highSpeedWifi: "WiFi haut débit",
    parkingAvailable: "Parking disponible",
    publicTransport: "Transport public accessible",
    modernOffices: "Bureaux modernes",
    reception: "Service d'accueil professionnel",
    quietEnvironment: "Environnement calme et productif",
    adminServices: "Assistance administrative",
    companyCreation: "Création d'entreprises",
    domiciliation: "Services de domiciliation",

    // Booking
    bookingTitle: "Réservez votre espace",
    selectSpace: "Sélectionnez votre espace",
    availableSpaces: "Espaces disponibles",
    reservedSpaces: "Espaces réservés",
    room1: "Salle 1 - Espace Collaboratif",
    room2: "Salle 2 - Zone Silencieuse",
    selectRoom: "Choisir la salle",

    // Services
    servicesTitle: "Nos Services",
    servicesSubtitle: "Solutions complètes pour votre activité professionnelle",
    coworkingService: "Espace de coworking moderne",
    coworkingDesc: "Espaces de travail flexibles dans un environnement collaboratif et inspirant",
    adminService: "Assistance administrative",
    adminDesc: "Support complet pour vos démarches administratives et gestion d'entreprise",
    domiciliationService: "Domiciliation d'entreprise",
    domiciliationDesc: "Adresse professionnelle prestigieuse pour votre société à Ariana",
    companyService: "Création d'entreprises",
    companyDesc: "Accompagnement personnalisé dans toutes vos démarches de création d'entreprise",

  },
  en: {
    // Add to the English translations object
premiumWorkspace: "Premium Workspace",
heroTitlePart1: "Productive & Modern",
heroTitlePart2: "Work Space",
heroSubtitle: "Work, collaborate, succeed in our modern professional space in Ariana. Book your space now.",
reserve: "Book Now",
contact: "Contact Us",
satisfactionRate: "Satisfaction Rate",
availability: "Availability",
happyMembers: "Happy Members",
freeHighSpeedWifi: "Free High Speed WiFi",
equippedMeetingRooms: "Equipped Meeting Rooms",
refreshmentsIncluded: "Refreshments Included",
wifiDescription: "Ultra-fast connection for uninterrupted work",
meetingRoomsDescription: "Modern rooms with complete equipment for your meetings",
refreshmentsDescription: "Coffee, tea and snacks available all day",
locationAddress: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
easyAccess: "Easy access, parking available",
    // Booking Page - Hero
    bookingHeroTitle: "Book Your Space",
    bookingHeroSubtitle: "Choose the perfect space for your productivity",
    bookingLocation: "Ariana, Tunisia",
    
    // Room Selection
    selectSpaceTitle: "Select Your Space - Colab Office Ariana",
    studyZone1: "Study Zone 1",
    studyZone2: "Study Zone 2",
    trainingRoom: "Training Room",
    meetingRoom: "Meeting Room",
    wholeRoomEquipment: "Whole room with professional equipment",
    quietProductiveArea: "Quiet and productive area for maximum concentration",
    
    // Legend
    studyZoneLegend: "Study zone (15 DT/day)",
    trainingRoomLegend: "Training (150 DT/day)",
    meetingRoomLegend: "Meeting (80 DT/day)",
    occupiedLegend: "Occupied",
    
    // Room Names
    quietStudyZone1: "Quiet Study Zone 1",
    quietStudyZone2: "Quiet Study Zone 2",
    trainingRoomName: "Training Room",
    meetingRoomName: "Meeting Room",
    entranceLabel: "Entrance",
    
    // Booking Form
    bookingFormTitle: "Booking",
    completeRoom: "Complete room",
    place: "Place",
    persons: "persons",
    
    // Duration Prices
    twoHours: "2 hours",
    halfDay: "Half day",
    fullDay: "Full day",
    
    // Space Types
    studyZoneType: "Study Zone",
    trainingRoomType: "Training Room",
    meetingRoomType: "Meeting Room",
    spaceType: "Space",
    
    // Features Section
    bookingFeaturesTitle: "Why Choose Colab Office?",
    bookingFeaturesSubtitle: "A modern and professional environment for your productivity",
    
    // Feature Cards
    quietEnvironmentFeature: "Quiet Environment",
    quietEnvironmentDesc: "Guaranteed silent zone for your concentration",
    flexibleHoursFeature: "Flexible Hours",
    flexibleHoursDesc: "Open from 8 AM to 10 PM, 7 days a week",
    completeServicesFeature: "Complete Services",
    completeServicesDesc: "Administrative assistance and company creation",
    idealLocationFeature: "Ideal Location",
    idealLocationDesc: "In the heart of Ariana, easily accessible",
    
    // Booking Form Fields
    selectDate: "Date",
    startTime: "Start Time",
    selectTime: "Select time",
    durationLabel: "Duration",
    totalLabel: "Total",
    
    // Actions
    bookNowButton: "Book Now",
    selectSpaceButton: "Select a place",
    selectSpacePrompt: "Click on an available space to start your booking",
    
    // Messages
    securePayment: "Secure payment",
    freeCancellation: "Free cancellation up to 2 hours before",
    perDay: "/day",
    
    // Time slots
    hours: [
      "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", 
      "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", 
      "20:00", "21:00"
    ],
    
    // Additional Booking Info
    capacity: "Capacity",
    includes: "Includes",
    dayRate: "Day rate",
    halfDayRate: "Half day rate",
    twoHoursRate: "2 hours rate",
    
    // Room Features
    projector: "Projector",
    whiteboard: "Whiteboard",
    wifi: "WiFi",
    airConditioning: "Air conditioning",
    seats: "seats",
    tvScreen: "TV Screen",
    videoConference: "Video conference",
    silence: "Silence",
    powerOutlet: "Power outlet",
    // Services Page
servicesPageTitle: "Rise Services - Our Solutions",
servicesPageSubtitle: "Modern coworking space, administrative assistance and business services in Ariana",
mainServicesTitle: "Our Main Services",
mainServicesSubtitle: "Complete solutions for your professional activity in a modern environment",
collaborative: "Collaborative",
openPrivateSpaces: "Open and private spaces",
freeHighSpeedWifi: "Free high-speed WiFi",
equippedMeetingRooms: "Equipped meeting rooms",
freeCoffeeTea: "Free coffee and tea",
perHour: "/hour",
reserve: "Reserve",
concentration: "Concentration",
studyZonesTitle: "Quiet study zones",
studyZonesDesc: "Dedicated study spaces in a calm and focused environment",
silenceGuaranteed: "Silence guaranteed",
electricOutlets: "Electric outlets at each seat",
optimalLighting: "Optimal lighting",
completeSupport: "Complete support",
adminServiceTitle: "Administrative assistance",
adminServiceDesc: "Complete support for your administrative procedures and business management",
companyCreationService: "Company creation",
adminFormalities: "Administrative formalities",
legalAdvice: "Legal advice",
personalizedSupport: "Personalized support",
onQuote: "On quote",
consult: "Consult",
prestigiousAddress: "Prestigious address",
domiciliationTitle: "Business domiciliation",
domiciliationDesc: "Prestigious professional address for your company in Ariana",
prestigiousCommercialAddress: "Prestigious commercial address",
mailReception: "Mail reception",
phoneService: "Phone service",
meetingRoomIncluded: "Meeting room included",
perMonth: "/month",
getInfo: "Get info",
includedServicesTitle: "Included Services",
includedServicesSubtitle: "All our spaces include these services for your comfort and productivity",
highSpeedWifiTitle: "High-speed WiFi",
highSpeedWifiDesc: "Fast and stable internet connection",
free: "Free",
coffeeTea: "Coffee & Tea",
coffeeTeaDesc: "Unlimited hot beverages",
electricOutletsTitle: "Electric outlets",
electricOutletsDesc: "At each workstation",
included: "Included",
quietEnvironmentTitle: "Quiet environment",
quietEnvironmentDesc: "Guaranteed quiet zones",
guaranteed: "Guaranteed",
readyToDiscover: "Ready to discover Rise Services?",
ctaServicesText: "Work, collaborate, succeed in our modern space in Ariana",
reserveSpace: "Reserve a space",
// ... all your existing English translations ...
    companyService: "Company creation",
    companyDesc: "Personalized support in all your company creation procedures",

    // About Page - ADD THESE
    aboutTitle: "About Colab Office",
    aboutSubtitle: "Your trusted partner for all your business needs in Tunisia. We have been supporting entrepreneurs in their success for over 10 years.",
    ourMission: "Our Mission",
    missionText1: "At Colab Office, we believe that every entrepreneur deserves professional and personalized support. Our mission is to simplify administrative and legal procedures to allow businesses to focus on their core business.",
    missionText2: "We offer complete solutions including administrative assistance & company creation, domiciliation & business services, as well as a modern coworking space in Ariana to promote collaboration and professional success.",
    companiesSupported: "Companies supported",
    yearsExperience: "Years of experience",
    isoCertified: "ISO 9001 Certified",
    qualityGuaranteed: "Quality guaranteed",
    ourValues: "Our Values",
    valuesPrinciples: "The principles that guide our daily work",
    trust: "Trust",
    trustDesc: "Transparency and integrity in all our client relationships",
    excellence: "Excellence",
    excellenceDesc: "Impeccable service quality and recognized expertise",
    responsiveness: "Responsiveness",
    responsivenessDesc: "Fast responses and efficient handling of your requests",
    proximity: "Proximity",
    proximityDesc: "Personalized support and close relationship",
    readyToStart: "Ready to start your project?",
    ctaText: "Benefit from our administrative assistance & company creation, domiciliation & business services in our modern space in Ariana",
    contactUs: "Contact us",    

    contactTitle: "Contact Us",
    contactSubtitle: "Our team is available to answer all your questions and assist you with your projects",
    contactFormTitle: "Send us a message",
    firstName: "First Name *",
    firstNamePlaceholder: "Your first name",
    lastName: "Last Name *",
    lastNamePlaceholder: "Your last name",
    email: "Email *",
    emailPlaceholder: "your.email@example.com",
    phone: "Phone",
    phonePlaceholder: "+216 XX XXX XXX",
    company: "Company",
    companyPlaceholder: "Your company name",
    service: "Desired Service",
    selectService: "Select a service",
    serviceDomiciliation: "Business domiciliation",
    serviceCreation: "Business creation",
    serviceJuridique: "Legal services",
    serviceComptabilite: "Accounting",
    serviceConsultation: "Free consultation",
    serviceOther: "Other",
    budget: "Approximate budget",
    selectBudget: "Select your budget",
    budgetLess500: "Less than 500 DT",
    budget5001000: "500 - 1000 DT",
    budget10002000: "1000 - 2000 DT",
    budgetMore2000: "More than 2000 DT",
    budgetMonthly: "Monthly subscription",
    message: "Message *",
    messagePlaceholder: "Describe your project or needs in detail...",
    urgentRequest: "Urgent request (response within 2h during business hours)",
    sendMessage: "Send Message",
    requiredFieldsNotice: "* Required fields. We will respond within 24h (2h for urgent requests).",
    contactInfoTitle: "Our Contact Info",
    address: "Address",
    addressLine1: "Avenue Yasser Arafat",
    addressLine2: "Sousse 4054, Tunisia",
    openingHours: "Opening Hours",
    hoursWeekdays: "Monday - Friday: 8:00 AM - 6:00 PM",
    hoursSaturday: "Saturday: 8:00 AM - 1:00 PM",
    hoursSunday: "Sunday: Closed",
    quickContactTitle: "Need a quick response?",
    quickContactText: "For an urgent consultation, call us directly or send a WhatsApp message.",
    callNow: "Call Now",
    whatsapp: "WhatsApp",
    findUsTitle: "Find Us",
    findUsSubtitle: "Located in the heart of Sousse, we are easily accessible",
    mapTitle: "Interactive Map",
    mapAddress: "Avenue Yasser Arafat, Sousse 4054",
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Answers to the most common questions",
    faq1Question: "How long does it take to get a business address?",
    faq1Answer: "Once we receive your complete file, we can provide your domiciliation certificate within 24 to 48 business hours. For urgent requests, we offer express service within 4 hours.",
    faq2Question: "Which documents are required for domiciliation?",
    faq2Answer: "You will need your company statutes, a copy of your ID, the duly completed domiciliation request form, and proof of activity. Our team will assist you in preparing the file.",
    faq3Question: "Do you offer services in other cities?",
    faq3Answer: "Yes, we have partners in the main cities of Tunisia: Tunis, Sfax, Monastir, Nabeul, and Gabès. We offer the same services with the same quality in all these cities.",
    faq4Question: "Can I change my plan during the subscription?",
    faq4Answer: "Absolutely! You can upgrade or downgrade your plan at any time. Changes take effect the following month and we adjust billing pro-rata.",
    faq5Question: "Do you offer a free consultation?",
    faq5Answer: "Yes, we offer a free 30-minute consultation to evaluate your needs and advise you on the best solution. Schedule an appointment via our contact form.",
    legal_title: "Legal Notice",
    legal_description: "Legal information and terms of use of our services",

    company_info_title: "Company Information",
    company_name_label: "Company Name",
    company_name: "Colab Office SARL",
    company_address_label: "Head Office",
    company_address: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    company_registry_label: "Commercial Registry",
    company_registry: "B051234567890",
    tax_id_label: "Tax ID",
    tax_id: "1234567/A/M/000",
    publication_director_label: "Publication Director",
    publication_director: "Rouache Schaima",
    contact_label: "Contact",
    email_label: "Email",
    contact_email: "contact.colab.office@gmail.com",
    phone_label: "Phone",
    contact_phone_number: "+216 54 824 791",

    cgu_title: "Terms of Use",  
    cgu_section_1_title: "1. Purpose",
    cgu_section_1_content: "These terms of use (TOU) define the conditions for using Colab Office's services and the rights and obligations of the parties involved.",
    cgu_section_2_title: "2. Acceptance of Terms",
    cgu_section_2_content: "Using our services implies full acceptance of these TOU. If you do not accept these terms, you must not use our services.",
    cgu_section_3_title: "3. Services Offered",
    cgu_section_3_content: "Colab Office offers the following services: Coworking space, Administrative assistance, Company creation and modification, Legal and administrative services, Business creation consulting, Secretarial and accounting services.",
    cgu_section_4_title: "4. Client Obligations",
    cgu_section_4_content: "The client agrees to provide accurate and up-to-date information, comply with applicable laws, pay invoices on time, and inform Colab Office of any changes in their situation.",
    cgu_section_5_title: "5. Pricing and Payment",
    cgu_section_5_content: "Service fees are indicated in Tunisian Dinar (DT) and may be revised. Payment is made according to the agreed terms at contract signing. Late payment may result in service suspension.",
    cgu_section_6_title: "6. Liability",
    cgu_section_6_content: "Colab Office commits to providing its services with diligence and professionalism. Liability is limited to direct damages and cannot exceed the amounts paid by the client.",
    cgu_section_7_title: "7. Termination",
    cgu_section_7_content: "The contract can be terminated by either party with one month's notice. Termination does not affect obligations already arisen.",
    cgu_section_8_title: "8. Governing Law",
    cgu_section_8_content: "These TOU are governed by Tunisian law. Any disputes fall under the exclusive jurisdiction of Sousse courts.",

    privacy_title: "Privacy Policy",
    privacy_section_1_title: "Data Collection",
    privacy_section_1_content: "We only collect personal data necessary for providing our services: name, surname, address, phone, email, and company information.",
    privacy_section_2_title: "Data Use",
    privacy_section_2_content: "Your data is used exclusively for file management, billing, and communication regarding our services. They are never sold or shared without consent.",
    privacy_section_3_title: "Data Retention",
    privacy_section_3_content: "Your data is retained during our contractual relationship and in accordance with legal obligations for accounting and legal document retention.",
    privacy_section_4_title: "Your Rights",
    privacy_section_4_content: "You have the right to access, correct, and delete your personal data. To exercise these rights, contact us at contact.colab.office@gmail.com.",

    cookies_title: "Cookie Policy",
    cookies_intro: "Our website uses cookies to enhance your browsing experience and analyze traffic. Cookies are small text files stored on your device.",
    cookies_types_label: "Types of cookies used:",
    cookie_type_technical: "Technical cookies: necessary for site functionality",
    cookie_type_analytics: "Analytics cookies: to measure audience and improve the site",
    cookie_type_preferences: "Preference cookies: to remember your choices",
    cookies_disable_note: "You can disable cookies in your browser settings, but this may affect site functionality.",

    last_updated: "Last update: January 2024",
    contact_questions: "For any questions regarding this legal notice, contact us at",
    contact_questions_email: "contact.colab.office@gmail.com",
    home: "Home",
    about: "About",
    services: "Services",
    booking: "Booking",
    contact: "Contact",
    faq: "FAQ",

    heroTitle: "Colab Office - Modern coworking space in Ariana",
    heroSubtitle: "Work, collaborate, succeed in our professional environment",
    heroDescription:
      "Modern coworking space in Ariana offering administrative assistance, company creation, domiciliation and business services in a collaborative environment.",
    getStarted: "Book Now",
    learnMore: "Learn More",

    // Location Section
    locationTitle: "Our space in Ariana",
    locationSubtitle: "A modern professional environment for your success",
    locationName: "Colab Office Ariana",
    locationCity: "Ariana",
    locationAddress: "14 Rue Ibn Elheni (Rond-point Borj Louzir), Ariana",
    locationDescription:
      "Discover our modern coworking space in Ariana. A perfect place to work, collaborate and develop your business with our administrative assistance and domiciliation services.",
    advantages: "Advantages",
    available: "Available",
    startingFrom: "Starting from",
    perMonth: "/month",
    perHour: "/hour",
    legal: "Legal",
    privacy: "Privacy",
    copyright: "© 2025 Colab Office - All rights reserved",

    // Features
    studyZones: "Quiet work spaces",
    coworkingSpace: "Collaborative coworking space",
    meetingRooms: "Equipped meeting rooms",
    highSpeedWifi: "High-speed WiFi",
    parkingAvailable: "Parking available",
    publicTransport: "Public transport accessible",
    modernOffices: "Modern offices",
    reception: "Professional reception service",
    quietEnvironment: "Calm and productive environment",
    adminServices: "Administrative assistance",
    companyCreation: "Company creation",
    domiciliation: "Domiciliation services",

    // Booking
    bookingTitle: "Book your space",
    selectSpace: "Select your space",
    availableSpaces: "Available spaces",
    reservedSpaces: "Reserved spaces",
    room1: "Room 1 - Collaborative Space",
    room2: "Room 2 - Quiet Zone",
    selectRoom: "Choose room",
    mapCity: "Tunis, Tunisia",
    getDirections: "Get Directions",
    callUs: "Call Us",
    seeOnGoogleMaps: "View on Google Maps",
    // Services
    servicesTitle: "Our Services",
    servicesSubtitle: "Complete solutions for your professional activity",
    coworkingService: "Modern coworking space",
    coworkingDesc: "Flexible workspaces in a collaborative and inspiring environment",
    adminService: "Administrative assistance",
    adminDesc: "Complete support for your administrative procedures and business management",
    domiciliationService: "Business domiciliation",
    domiciliationDesc: "Prestigious professional address for your company in Ariana",
    companyService: "Company creation",
    companyDesc: "Personalized support in all your company creation procedures",

  },
  ar: {
// Add to the Arabic translations object
premiumWorkspace: "مساحة عمل متميزة",
heroTitlePart1: "منتج وحديث",
heroTitlePart2: "مساحة العمل",
heroSubtitle: "اعمل، تعاون، انجح في مساحتنا المهنية الحديثة في أريانة. احجز مساحتك الآن.",
reserve: "احجز الآن",
contact: "اتصل بنا",
satisfactionRate: "معدل الرضا",
availability: "التوفر",
happyMembers: "أعضاء سعداء",
freeHighSpeedWifi: "واي فاي عالي السرعة مجاناً",
equippedMeetingRooms: "قاعات اجتماعات مجهزة",
refreshmentsIncluded: "مشروبات مدرجة",
wifiDescription: "اتصال فائق السرعة للعمل دون انقطاع",
meetingRoomsDescription: "غرف حديثة مع معدات كاملة لاجتماعاتك",
refreshmentsDescription: "قهوة، شاي ووجبات خفيفة متاحة طوال اليوم",
locationAddress: "14 شارع ابن الهاني (دوار برج لوزير)، أريانة",
easyAccess: "وصول سهل، موقف سيارات متاح",
    // Booking Page - Hero
    bookingHeroTitle: "احجز مساحتك",
    bookingHeroSubtitle: "اختر المساحة المثالية لإنتاجيتك",
    bookingLocation: "أريانة، تونس",
    
    // Room Selection
    selectSpaceTitle: "اختر مساحتك - كولاب أوفيس أريانة",
    studyZone1: "منطقة الدراسة 1",
    studyZone2: "منطقة الدراسة 2",
    trainingRoom: "قاعة التدريب",
    meetingRoom: "قاعة الاجتماعات",
    wholeRoomEquipment: "قاعة كاملة مع معدات مهنية",
    quietProductiveArea: "منطقة هادئة ومنتجة لأقصى تركيز",
    
    // Legend
    studyZoneLegend: "منطقة الدراسة (15 دينار/يوم)",
    trainingRoomLegend: "تدريب (150 دينار/يوم)",
    meetingRoomLegend: "اجتماع (80 دينار/يوم)",
    occupiedLegend: "محجوز",
    
    // Room Names
    quietStudyZone1: "منطقة الدراسة الهادئة 1",
    quietStudyZone2: "منطقة الدراسة الهادئة 2",
    trainingRoomName: "قاعة التدريب",
    meetingRoomName: "قاعة الاجتماعات",
    entranceLabel: "المدخل",
    
    // Booking Form
    bookingFormTitle: "الحجز",
    completeRoom: "قاعة كاملة",
    place: "مكان",
    persons: "أشخاص",
    
    // Duration Prices
    twoHours: "ساعتين",
    halfDay: "نصف يوم",
    fullDay: "يوم كامل",
    
    // Space Types
    studyZoneType: "منطقة الدراسة",
    trainingRoomType: "قاعة التدريب",
    meetingRoomType: "قاعة الاجتماعات",
    spaceType: "مساحة",
    
    // Features Section
    bookingFeaturesTitle: "لماذا تختار كولاب أوفيس؟",
    bookingFeaturesSubtitle: "بيئة حديثة واحترافية لإنتاجيتك",
    
    // Feature Cards
    quietEnvironmentFeature: "بيئة هادئة",
    quietEnvironmentDesc: "منطقة صامتة مضمونة لتركيزك",
    flexibleHoursFeature: "ساعات مرنة",
    flexibleHoursDesc: "مفتوح من الساعة 8 صباحاً حتى 10 مساءً، 7 أيام في الأسبوع",
    completeServicesFeature: "خدمات كاملة",
    completeServicesDesc: "المساعدة الإدارية وإنشاء الشركات",
    idealLocationFeature: "موقع مثالي",
    idealLocationDesc: "في قلب أريانة، يسهل الوصول إليه",
    
    // Booking Form Fields
    selectDate: "التاريخ",
    startTime: "وقت البدء",
    selectTime: "اختر الوقت",
    durationLabel: "المدة",
    totalLabel: "الإجمالي",
    
    // Actions
    bookNowButton: "احجز الآن",
    selectSpaceButton: "اختر مكاناً",
    selectSpacePrompt: "انقر على مكان متاح لبدء الحجز",
    
    // Messages
    securePayment: "دفع آمن",
    freeCancellation: "إلغاء مجاني حتى ساعتين قبل",
    perDay: "/يوم",
    
    // Time slots
    hours: [
      "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", 
      "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", 
      "20:00", "21:00"
    ],
    
    // Additional Booking Info
    capacity: "السعة",
    includes: "يشمل",
    dayRate: "سعر اليوم",
    halfDayRate: "سعر نصف اليوم",
    twoHoursRate: "سعر ساعتين",
    
    // Room Features
    projector: "عارض",
    whiteboard: "لوح أبيض",
    wifi: "واي فاي",
    airConditioning: "مكيف هواء",
    seats: "مقاعد",
    tvScreen: "شاشة تلفزيون",
    videoConference: "مؤتمر فيديو",
    silence: "صمت",
    powerOutlet: "مقبس كهرباء",
// Services Page
servicesPageTitle: "رايز سيرفيسز - حلولنا",
servicesPageSubtitle: "مساحة عمل مشتركة حديثة، مساعدة إدارية وخدمات أعمال في أريانة",
mainServicesTitle: "خدماتنا الرئيسية",
mainServicesSubtitle: "حلول شاملة لنشاطك المهني في بيئة حديثة",
collaborative: "تعاوني",
openPrivateSpaces: "مساحات مفتوحة وخاصة",
freeHighSpeedWifi: "واي فاي مجاني عالي السرعة",
equippedMeetingRooms: "قاعات اجتماعات مجهزة",
freeCoffeeTea: "قهوة وشاي مجاني",
perHour: "/ساعة",
reserve: "احجز",
concentration: "تركيز",
studyZonesTitle: "مناطق دراسة هادئة",
studyZonesDesc: "مساحات مخصصة للدراسة في بيئة هادئة ومركزة",
silenceGuaranteed: "الصمت مضمون",
electricOutlets: "مقابس كهربائية في كل مكان",
optimalLighting: "إضاءة مثالية",
completeSupport: "دعم كامل",
adminServiceTitle: "المساعدة الإدارية",
adminServiceDesc: "دعم كامل لإجراءاتك الإدارية وإدارة الأعمال",
companyCreationService: "إنشاء الشركات",
adminFormalities: "الإجراءات الإدارية",
legalAdvice: "استشارات قانونية",
personalizedSupport: "دعم شخصي",
onQuote: "حسب الطلب",
consult: "استشر",
prestigiousAddress: "عنوان مرموق",
domiciliationTitle: "تسكين الشركات",
domiciliationDesc: "عنوان مهني مرموق لشركتك في أريانة",
prestigiousCommercialAddress: "عنوان تجاري مرموق",
mailReception: "استقبال البريد",
phoneService: "خدمة هاتفية",
meetingRoomIncluded: "قاعة اجتماعات مشمولة",
perMonth: "/شهر",
getInfo: "احصل على معلومات",
includedServicesTitle: "الخدمات المشمولة",
includedServicesSubtitle: "جميع مساحاتنا تشمل هذه الخدمات لراحتك وإنتاجيتك",
highSpeedWifiTitle: "واي فاي عالي السرعة",
highSpeedWifiDesc: "اتصال إنترنت سريع ومستقر",
free: "مجاني",
coffeeTea: "قهوة وشاي",
coffeeTeaDesc: "مشروبات ساخنة بلا حدود",
electricOutletsTitle: "مقابس كهربائية",
electricOutletsDesc: "في كل مكان عمل",
included: "مشمول",
quietEnvironmentTitle: "بيئة هادئة",
quietEnvironmentDesc: "مناطق هادئة مضمونة",
guaranteed: "مضمون",
readyToDiscover: "هل أنت مستعد لاكتشاف رايز سيرفيسز؟",
ctaServicesText: "اعمل، تعاون، انجح في مساحتنا الحديثة في أريانة",
reserveSpace: "احجز مساحة",
    companyService: "إنشاء الشركات",
    companyDesc: "مرافقة شخصية في جميع إجراءات إنشاء شركتك",

    // About Page - ADD THESE
    aboutTitle: "حول كولاب أوفيس",
    aboutSubtitle: "شريكك الموثوق لجميع احتياجات عملك في تونس. نرافق رواد الأعمال في نجاحهم منذ أكثر من 10 سنوات.",
    ourMission: "مهمتنا",
    missionText1: "في كولاب أوفيس، نؤمن بأن كل رائد أعمال يستحق دعمًا مهنيًا وشخصيًا. مهمتنا هي تبسيط الإجراءات الإدارية والقانونية للسماح للشركات بالتركيز على أعمالها الأساسية.",
    missionText2: "نقدم حلولاً شاملة تشمل المساعدة الإدارية وإنشاء الشركات، والتسكين وخدمات الأعمال، بالإضافة إلى مساحة عمل مشتركة حديثة في أريانة لتعزيز التعاون والنجاح المهني.",
    companiesSupported: "الشركات المدعومة",
    yearsExperience: "سنوات من الخبرة",
    isoCertified: "معتمد ISO 9001",
    qualityGuaranteed: "جودة مضمونة",
    ourValues: "قيمنا",
    valuesPrinciples: "المبادئ التي توجه عملنا اليومي",
    trust: "الثقة",
    trustDesc: "الشفافية والنزاهة في جميع علاقاتنا مع العملاء",
    excellence: "التميز",
    excellenceDesc: "جودة خدمة لا تشوبها شائبة وخبرة معترف بها",
    responsiveness: "السرعة",
    responsivenessDesc: "ردود سريعة ومعالجة فعالة لطلباتك",
    proximity: "القرب",
    proximityDesc: "دعم شخصي وعلاقة قريبة",
    readyToStart: "هل أنت مستعد لبدء مشروعك؟" ,
    ctaText: "استفد من مساعدتنا الإدارية وإنشاء الشركات، والتسكين وخدمات الأعمال في مساحتنا الحديثة في أريانة",
    contactUs: "اتصل بنا",

    mapCity: "تونس، تونس",
    getDirections: "الحصول على الاتجاهات",
    callUs: "اتصل بنا",
    seeOnGoogleMaps: "عرض على خرائط جوجل",
    
    // ... your existing translations
    contactTitle: "اتصل بنا",
    contactSubtitle: "فريقنا متاح للإجابة على جميع أسئلتك ومساعدتك في مشاريعك",
    contactFormTitle: "أرسل لنا رسالة",
    firstName: "الاسم الأول *",
    firstNamePlaceholder: "اسمك الأول",
    lastName: "الاسم الأخير *",
    lastNamePlaceholder: "اسم العائلة",
    email: "البريد الإلكتروني *",
    emailPlaceholder: "your.email@example.com",
    phone: "رقم الهاتف",
    phonePlaceholder: "+216 XX XXX XXX",
    company: "الشركة",
    companyPlaceholder: "اسم شركتك",
    service: "الخدمة المطلوبة",
    selectService: "اختر خدمة",
    serviceDomiciliation: "تسجيل شركة",
    serviceCreation: "إنشاء شركة",
    serviceJuridique: "الخدمات القانونية",
    serviceComptabilite: "المحاسبة",
    serviceConsultation: "استشارة مجانية",
    serviceOther: "أخرى",
    budget: "الميزانية التقريبية",
    selectBudget: "اختر ميزانيتك",
    budgetLess500: "أقل من 500 دينار",
    budget5001000: "500 - 1000 دينار",
    budget10002000: "1000 - 2000 دينار",
    budgetMore2000: "أكثر من 2000 دينار",
    budgetMonthly: "اشتراك شهري",
    message: "الرسالة *",
    messagePlaceholder: "صف مشروعك أو احتياجاتك بالتفصيل...",
    urgentRequest: "طلب عاجل (الرد خلال ساعتين أثناء ساعات العمل)",
    sendMessage: "إرسال الرسالة",
    requiredFieldsNotice: "* الحقول المطلوبة. سنرد خلال 24 ساعة (ساعتين للطلبات العاجلة).",
    contactInfoTitle: "معلومات الاتصال",
    address: "العنوان",
    addressLine1: "شارع ياسر عرفات",
    addressLine2: "سوسة 4054، تونس",
    openingHours: "ساعات العمل",
    hoursWeekdays: "الاثنين - الجمعة: 8:00 - 18:00",
    hoursSaturday: "السبت: 8:00 - 13:00",
    hoursSunday: "الأحد: مغلق",
    quickContactTitle: "هل تحتاج لرد سريع؟",
    quickContactText: "للاستشارة العاجلة، اتصل بنا مباشرة أو أرسل رسالة واتساب.",
    callNow: "اتصل الآن",
    whatsapp: "واتساب",
    findUsTitle: "أين تجدنا",
    findUsSubtitle: "موقعنا في قلب سوسة، ويمكن الوصول إلينا بسهولة",
    mapTitle: "خريطة تفاعلية",
    mapAddress: "شارع ياسر عرفات، سوسة 4054",
    faqTitle: "الأسئلة المتكررة",
    faqSubtitle: "إجابات على أكثر الأسئلة شيوعًا",
    faq1Question: "كم من الوقت يستغرق الحصول على عنوان للشركة؟",
    faq1Answer: "بعد استلام ملفك الكامل، يمكننا توفير شهادة التوطين الخاصة بك خلال 24 إلى 48 ساعة عمل. للطلبات العاجلة، نقدم خدمة سريعة خلال 4 ساعات.",
    faq2Question: "ما هي الوثائق المطلوبة للتوطين؟",
    faq2Answer: "ستحتاج إلى النظام الأساسي لشركتك، نسخة من هويتك، نموذج طلب التوطين مكتمل، وإثبات النشاط. فريقنا سيرشدك في إعداد الملف.",
    faq3Question: "هل تقدمون خدمات في مدن أخرى؟",
    faq3Answer: "نعم، لدينا شركاء في المدن الرئيسية في تونس: تونس، صفاقس، المنستير، نابل، وقابس. نحن نقدم نفس الخدمات بنفس الجودة في جميع هذه المدن.",
    faq4Question: "هل يمكنني تغيير الخطة أثناء الاشتراك؟",
    faq4Answer: "بالتأكيد! يمكنك ترقية أو تخفيض خطتك في أي وقت. تصبح التغييرات سارية في الشهر التالي ونقوم بتعديل الفوترة حسب النسبة.",
    faq5Question: "هل تقدمون استشارة مجانية؟",
    faq5Answer: "نعم، نقدم استشارة مجانية لمدة 30 دقيقة لتقييم احتياجاتك وإرشادك إلى أفضل الحلول. احجز موعدًا عبر نموذج الاتصال.",
    legal_title: "الشروط والأحكام",
    legal_description: "المعلومات القانونية وشروط استخدام خدماتنا",

    company_info_title: "معلومات الشركة",
    company_name_label: "اسم الشركة",
    company_name: "شركة رايز سيرفيسز",
    company_address_label: "المقر الرئيسي",
    company_address: "شارع ياسر عرفات، سوسة 4054، تونس",
    company_registry_label: "السجل التجاري",
    company_registry: "B051234567890",
    tax_id_label: "الرقم الضريبي",
    tax_id: "1234567/A/M/000",
    publication_director_label: "مدير النشر",
    publication_director: "أحمد صالحي",
    contact_label: "الاتصال",
    email_label: "البريد الإلكتروني",
    contact_email: "contact.colab.office@gmail.com",
    phone_label: "الهاتف",
    contact_phone_number: "+216 54 824 791",

    cgu_title: "الشروط والأحكام",
    cgu_section_1_title: "1. الهدف",
    cgu_section_1_content: "تهدف هذه الشروط لتحديد شروط استخدام خدمات كولاب أوفيس وحقوق والتزامات الأطراف.",
    cgu_section_2_title: "2. قبول الشروط",
    cgu_section_2_content: "استخدام خدماتنا يعني القبول الكامل لهذه الشروط. إذا لم توافق على هذه الشروط، يجب عدم استخدام خدماتنا.",
    cgu_section_3_title: "3. الخدمات المقدمة",
    cgu_section_3_content: "تقدم رايز سيرفيسز الخدمات التالية: التسكين، إنشاء وتعديل الشركات، الخدمات القانونية والإدارية، الاستشارات في إنشاء الشركات، خدمات السكرتارية والمحاسبة.",
    cgu_section_4_title: "4. التزامات العميل",
    cgu_section_4_content: "يجب على العميل تقديم معلومات دقيقة ومحدثة، الالتزام بالقوانين، دفع الفواتير في الوقت المحدد، وإبلاغ رايز سيرفيسز بأي تغييرات في وضعه.",
    cgu_section_5_title: "5. الأسعار والدفع",
    cgu_section_5_content: "الأسعار بالعملة التونسية (DT) وقابلة للتعديل. يتم الدفع وفق الشروط المتفق عليها عند توقيع العقد. التأخير في الدفع قد يؤدي إلى تعليق الخدمات.",
    cgu_section_6_title: "6. المسؤولية",
    cgu_section_6_content: "تلتزم رايز سيرفيسز بتقديم خدماتها بمهارة ومهنية. المسؤولية محدودة بالأضرار المباشرة ولا تتجاوز المبالغ المدفوعة من قبل العميل.",
    cgu_section_7_title: "7. إنهاء العقد",
    cgu_section_7_content: "يمكن لأي طرف إنهاء العقد مع إشعار مسبق لمدة شهر. لا يؤثر الإنهاء على الالتزامات المتحققة بالفعل.",
    cgu_section_8_title: "8. القانون المطبق",
    cgu_section_8_content: "تخضع هذه الشروط للقانون التونسي. أي نزاعات تكون من اختصاص محاكم سوسة.",

    privacy_title: "سياسة الخصوصية",
    privacy_section_1_title: "جمع البيانات",
    privacy_section_1_content: "نقوم بجمع البيانات الشخصية الضرورية فقط لتقديم خدماتنا: الاسم، العنوان، الهاتف، البريد الإلكتروني، ومعلومات الشركة.",
    privacy_section_2_title: "استخدام البيانات",
    privacy_section_2_content: "يتم استخدام بياناتك فقط لإدارة ملفك، الفوترة، والتواصل بخصوص خدماتنا. لا يتم بيعها أو نقلها لطرف ثالث بدون موافقتك.",
    privacy_section_3_title: "الاحتفاظ بالبيانات",
    privacy_section_3_content: "يتم الاحتفاظ ببياناتك طوال فترة العلاقة التعاقدية ووفق الالتزامات القانونية للوثائق المحاسبية والقانونية.",
    privacy_section_4_title: "حقوقك",
    privacy_section_4_content: "لديك الحق في الوصول إلى بياناتك الشخصية وتصحيحها وحذفها. لممارسة هذه الحقوق، اتصل بنا على contact@riseservices.tn.",

    cookies_title: "سياسة الكوكيز",
    cookies_intro: "يستخدم موقعنا ملفات الكوكيز لتحسين تجربة التصفح وتحليل الحركة. الكوكيز هي ملفات نصية صغيرة مخزنة على جهازك.",
    cookies_types_label: "أنواع الكوكيز المستخدمة:",
    cookie_type_technical: "كوكيز تقنية: ضرورية لتشغيل الموقع",
    cookie_type_analytics: "كوكيز تحليلية: لقياس الجمهور وتحسين الموقع",
    cookie_type_preferences: "كوكيز تفضيلات: لحفظ اختياراتك",
    cookies_disable_note: "يمكنك تعطيل الكوكيز في إعدادات المتصفح، لكن هذا قد يؤثر على عمل الموقع.",

    last_updated: "آخر تحديث: يناير 2024",
    contact_questions: "لأي استفسارات حول الشروط والأحكام، اتصل بنا على",
    contact_questions_email: "contact.colab.office@gmail.com",
    home: "الرئيسية",
    about: "حولنا",
    services: "الخدمات",
    booking: "الحجز",
    contact: "اتصل بنا",
    faq: "الأسئلة الشائعة",

    heroTitle: "كولاب أوفيس - مساحة عمل مشتركة حديثة في أريانة",
    heroSubtitle: "اعمل، تعاون، انجح في بيئتنا المهنية",
    heroDescription:
      "مساحة عمل مشتركة حديثة في أريانة تقدم المساعدة الإدارية وإنشاء الشركات والتسكين وخدمات الأعمال في بيئة تعاونية.",
    getStarted: "احجز الآن",
    learnMore: "اعرف المزيد",

    locationTitle: "مساحتنا في أريانة",
    locationSubtitle: "بيئة مهنية حديثة لنجاحك",
    locationName: "كولاب أوفيس أريانة",
    locationCity: "أريانة",
    locationAddress: "14 شارع ابن الهاني (دوار برج لوزير)، أريانة",
    locationDescription:
      "اكتشف مساحة العمل المشتركة الحديثة في أريانة. مكان مثالي للعمل والتعاون وتطوير أعمالك مع خدمات المساعدة الإدارية والتسكين.",
    advantages: "المزايا",
    available: "متاح",
    startingFrom: "ابتداء من",
    perMonth: "/شهر",
    perHour: "/ساعة",
    legal: "الشروط والأحكام",
    privacy: "الخصوصية",
    
    studyZones: "مساحات عمل هادئة",
    coworkingSpace: "مساحة عمل مشتركة تعاونية",
    meetingRooms: "قاعات اجتماعات مجهزة",
    highSpeedWifi: "إنترنت عالي السرعة",
    parkingAvailable: "موقف سيارات متاح",
    publicTransport: "النقل العام متاح",
    modernOffices: "مكاتب حديثة",
    reception: "خدمة استقبال مهنية",
    quietEnvironment: "بيئة هادئة ومنتجة",
    adminServices: "المساعدة الإدارية",
    companyCreation: "إنشاء الشركات",
    domiciliation: "خدمات التسكين",
    copyright: "© 2025 كولاب أوفيس - جميع الحقوق محفوظة",

    bookingTitle: "احجز مساحتك",
    selectSpace: "اختر مساحتك",
    availableSpaces: "المساحات المتاحة",
    reservedSpaces: "المساحات المحجوزة",
    room1: "القاعة 1 - مساحة تعاونية",
    room2: "القاعة 2 - منطقة هادئة",
    selectRoom: "اختر القاعة",

    servicesTitle: "خدماتنا",
    servicesSubtitle: "حلول شاملة لنشاطك المهني",
    coworkingService: "مساحة عمل مشتركة حديثة",
    coworkingDesc: "مساحات عمل مرنة في بيئة تعاونية وملهمة",
    adminService: "المساعدة الإدارية",
    adminDesc: "دعم كامل لإجراءاتك الإدارية وإدارة الأعمال",
    domiciliationService: "تسكين الشركات",
    domiciliationDesc: "عنوان مهني مرموق لشركتك في أريانة",
    companyService: "إنشاء الشركات",
    companyDesc: "مرافقة شخصية في جميع إجراءات إنشاء شركتك",
  },
}

export function useLanguage() {
  const [currentLang, setCurrentLang] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("preferred-language") || "fr"
    }
    return "fr"
  })
  
  useEffect(() => {
    const handleLanguageChange = (event: CustomEvent) => {
      setCurrentLang(event.detail)
    }
  
    window.addEventListener("languageChange", handleLanguageChange as EventListener)
  
    return () => {
      window.removeEventListener("languageChange", handleLanguageChange as EventListener)
    }
  }, [])

  const t = (key: string) => {
    return translations[currentLang as keyof typeof translations]?.[key as keyof (typeof translations)["fr"]] || key
  }

  return { currentLang, t }
}
